alias ls='ls --color=auto'
alias ll='ls -ahlF'
alias la='ls -A'
alias l='ls -CF'
alias lld='ll --group-directories-first'
alias ld='l --group-directories-first'

alias python='python3'
alias py='python'
alias py_pdb='python -m pdb -c continue'
alias pip='pip3'

alias vim='nvim'
alias vi='nvim'
alias v='nvim'

alias sshx='ssh -X'
alias op='gio open'
alias bat='batcat'
alias f='find . -name '
